sudo: required

language: node_js

services:
  - docker

before_install:
- node -v
- npm install -g mocha
- docker build -t zakaria/devops .
- docker run -d -p 3000:3000 zakaria/devops 
- docker ps -a

script:
- npm run test